# What is a reasonable diffusion coefficient for transported cargo?

Single-particle tracking studies suggest that cargo undergoes long unidirectional runs in addition to bidirectional movements ([Dynes & Steward, 2006](http://dx.doi.org/10.1002/cne.21189), [Soundararajan & Bullock, 2014](http://dx.doi.org/10.7554/eLife.01596#sthash.owQem7IU.dpuf)). The unidirectional runs can lead to enhanced diffusion (supra-linear increases in mean-squared displacement over time); however, if particles fluctuate between unidirectional and bidirectional movement statistics, then it is plausible that the ensemble can be well-approximated by a single drift-diffusion process over long time periods ([Caspi, 2000](http://dx.doi.org/10.1103/PhysRevLett.85.5655)).

In this notebook we explore what the effective diffusion coefficient might plausibly be in a biological system.

We model the movement of particles as a discrete-time random walk. The particles fluctuate between three states:

* $S_0$ : bidirectional state (pure diffusion)
* $S_+$ : Anterograde unidirectional movement
* $S_-$ : Retrograde unidirectional movement

The displacement of the particle, $x$, follows the discrete-time dynamics:

$$
x_{n+1} = (x_n + 1)p_+ + x_n p_0 + (x_n - 1)p_-
$$

where the probability of stepping right, nowhere, and left are respectively: $\{p_+, p_0, p_-\}$. These probabilities are:

$$
p_+ = p \left ( +~ \big | ~S_+ \right) p(S_+) + p \left ( +~ \big | ~S_0 \right) p(S_0)
$$

$$
p_0 = p \left ( 0~ \big | ~s_u \right) p(S_0)
$$

$$
p_- = p \left ( -~ \big | ~S_- \right) p(S_-) + p \left ( -~ \big | ~S_0 \right) p(S_0)
$$

We further assume that the bidirectional movement state has no drift term, which means:

$$
p \left ( +~ \big | ~S_0 \right) = p \left ( -~ \big | ~S_0 \right)
$$

To get a handle on this system, we assume that the transitions matrix is symmetric. As a consequence, there is no overall drift to the system &mdash; we make this simplification because we are interested in estimating reasonable bounds on the diffusion coefficient.

$$
Q = \begin{bmatrix}
    p_{S_+ \rightarrow S_+} & p_{S_0 \rightarrow S_+} & p_{S_- \rightarrow S_+} \\
    p_{S_+ \rightarrow S_0} & p_{S_0 \rightarrow S_0} & p_{S_- \rightarrow S_0} \\
    p_{S_+ \rightarrow S_-} & p_{S_0 \rightarrow S_-} & p_{S_- \rightarrow S_-}
\end{bmatrix} = \begin{bmatrix}
    1-a-b & a & b \\
    a & 1-2a & a \\
    b & a & 1-a-b
\end{bmatrix}
$$

The state-transition matrix of the entire system (including transitions between $S$ and changes in position, $x$) is:

$$
\{x+1,S_+\} \\
\{x,S_+\} \\
\{x-1,S_+\} \\
\{x+1,S_0\} \\
\{x,S_0\} \\
\{x-1,S_0\} \\
\{x+1,S_-\} \\
\{x,S_-\} \\
\{x-1,S_-\} \\
$$

$$
M = \begin{bmatrix}
    p_{\{x,S_0\} \rightarrow \{x+1,S_0\}} \\
    p_{\{x,S_0\} \rightarrow \{x+1,S_+\}} \\
    p_{\{x,S_0\} \rightarrow \{x+1,S_-\}} \\
    p_{\{x,S_0\} \rightarrow \{x,S_0\}} \\
    p_{\{x,S_0\} \rightarrow \{x,S_+\}} \\
    p_{\{x,S_0\} \rightarrow \{x,S_-\}} \\
    p_{\{x,S_0\} \rightarrow \{x-1,S_0\}} \\
    p_{\{x,S_0\} \rightarrow \{x-1,S_+\}} \\
    p_{\{x,S_0\} \rightarrow \{x-1,S_-\}}
\end{bmatrix}
$$


$$
\begin{array}
pp_{\{x-1,S_-\} \rightarrow \{x,S_0\}} & p_{\{x,S_-\} \rightarrow \{x,S_0\}} & p_{\{x+1,S_-\} \rightarrow \{x,S_0\}} & p_{\{x-1,S_0\} \rightarrow \{x,S_0\}} & p_{\{x,S_0\} \rightarrow \{x,S_0\}} & p_{\{x+1,S_0\} \rightarrow \{x,S_0\}} & p_{\{x-1,S_+\} \rightarrow \{x,S_0\}} & p_{\{x,S_+\} \rightarrow \{x,S_0\}} & p_{\{x+1,S_+\} \rightarrow \{x,S_0\}}
\end{array}
$$

$$
\begin{array}
pp_{\{x-1,S_-\} \rightarrow \{x-1,S_-\}} &
p_{\{x-1,S_0\} \rightarrow \{x-1,S_-\}} &
p_{\{x-1,S_+\} \rightarrow \{x-1,S_-\}} &
p_{\{x,S_-\} \rightarrow \{x-1,S_-\}} &
p_{\{x,S_0\} \rightarrow \{x-1,S_-\}} &
p_{\{x,S_+\} \rightarrow \{x-1,S_-\}} &
p_{\{x+1,S_-\} \rightarrow \{x-1,S_-\}} &
p_{\{x+1,S_0\} \rightarrow \{x-1,S_-\}} &
p_{\{x+1,S_+\} \rightarrow \{x-1,S_-\}} \\
p_{\{x-1,S_-\} \rightarrow \{x-1,S_0\}} &
p_{\{x-1,S_0\} \rightarrow \{x-1,S_0\}} &
p_{\{x-1,S_+\} \rightarrow \{x-1,S_0\}} &
p_{\{x,S_-\} \rightarrow \{x-1,S_0\}} &
p_{\{x,S_0\} \rightarrow \{x-1,S_0\}} &
p_{\{x,S_+\} \rightarrow \{x-1,S_0\}} &
p_{\{x+1,S_-\} \rightarrow \{x-1,S_0\}} &
p_{\{x+1,S_0\} \rightarrow \{x-1,S_0\}} &
p_{\{x+1,S_+\} \rightarrow \{x-1,S_0\}} \\
p_{\{x-1,S_-\} \rightarrow \{x-1,S_+\}} &
p_{\{x-1,S_0\} \rightarrow \{x-1,S_+\}} &
p_{\{x-1,S_+\} \rightarrow \{x-1,S_+\}} &
p_{\{x,S_-\} \rightarrow \{x-1,S_+\}} &
p_{\{x,S_0\} \rightarrow \{x-1,S_+\}} &
p_{\{x,S_+\} \rightarrow \{x-1,S_+\}} &
p_{\{x+1,S_-\} \rightarrow \{x-1,S_+\}} &
p_{\{x+1,S_0\} \rightarrow \{x-1,S_+\}} &
p_{\{x+1,S_+\} \rightarrow \{x-1,S_+\}} \\
p_{\{x-1,S_-\} \rightarrow \{x,S_-\}} &
p_{\{x-1,S_0\} \rightarrow \{x,S_-\}} &
p_{\{x-1,S_+\} \rightarrow \{x,S_-\}} &
p_{\{x,S_-\} \rightarrow \{x,S_-\}} &
p_{\{x,S_0\} \rightarrow \{x,S_-\}} &
p_{\{x,S_+\} \rightarrow \{x,S_-\}} &
p_{\{x+1,S_-\} \rightarrow \{x,S_-\}} &
p_{\{x+1,S_0\} \rightarrow \{x,S_-\}} &
p_{\{x+1,S_+\} \rightarrow \{x,S_-\}} \\
p_{\{x-1,S_-\} \rightarrow \{x,S_0\}} &
p_{\{x-1,S_0\} \rightarrow \{x,S_0\}} &
p_{\{x-1,S_+\} \rightarrow \{x,S_0\}} &
p_{\{x,S_-\} \rightarrow \{x,S_0\}} &
p_{\{x,S_0\} \rightarrow \{x,S_0\}} &
p_{\{x,S_+\} \rightarrow \{x,S_0\}} &
p_{\{x+1,S_-\} \rightarrow \{x,S_0\}} &
p_{\{x+1,S_0\} \rightarrow \{x,S_0\}} &
p_{\{x+1,S_+\} \rightarrow \{x,S_0\}}
\end{array}
$$

We assume that each time step is one second and each movement is 1 micron. This leads to a single-particle velocity of 60 microns per minute in the unidirectional state, which is in rough agreement with the maximal velocities in experimental measurments ([Dynes & Steward, 2006](http://dx.doi.org/10.1002/cne.21189), [Soundararajan & Bullock, 2014](http://dx.doi.org/10.7554/eLife.01596#sthash.owQem7IU.dpuf)).

[Soundararajan & Bullock (2014)](http://dx.doi.org/10.7554/eLife.01596#sthash.owQem7IU.dpuf) estimate the diffusion coefficient *for bidirectional transport* to be $D = \sigma^2/2 =$ ~0.08 $\mu m^2 / s$ in *Drosophila* embryos, which appears roughly in line with other reports ([Caspi, 2000](http://dx.doi.org/10.1103/PhysRevLett.85.5655)). The variance of the random walk, $\sigma^2$, after $n$ time steps in state $s_b$ is given by:

$$ \sigma^2_n ~\big |~s_b = n \cdot 0.16~\mu m^2 / s =  n \left( p \left ( +~ \big | ~s_b \right) +  p \left ( -~ \big | ~s_b \right) - \left [ p \left ( +~ \big | ~s_b \right) - p \left ( -~ \big | ~s_b \right) \right ]^2 \right)$$

# Simulations to confirm the above analysis:

In [46]:
import numpy as np
import pylab as plt
from scipy import stats
%matplotlib inline

In [51]:
dt,tmax = 1,120 # seconds

def get_Q(a,b):
    Q = np.array([[1-a-b,   b  ,   a  ],
                  [  b  , 1-2*b,   b  ],
                  [  a  ,   b  , 1-a-b]])
    w,v = np.linalg.eig(Q)
    iw = np.argmax(w)
    p_state = v[:,iw]/np.sum(v[:,iw]) # [p(s-),p(s0),p(s+)]
    p_bidir = np.array([0.08,0.84,0.08]) # p(-|s0),p(0|s0),p(+|s0)
    return Q,p_state,p_bidir

def update(x,s):
    # Draw a new state
    s.append(np.random.choice(range(3),p=Q[:,s[-1]].flatten()))
    # Update position
    if s[-1] == 0:
        x.append(x[-1]-1)
    elif s[-1] == 2:
        x.append(x[-1]+1)
    else:
        x.append(x[-1]+np.random.choice(range(3),p=p_bidir)-1)

def markov_sim():
    """
    n = number of simulations to run (only last sim is returned)
    """    
    x = [0]          # initial position
    s = [np.random.choice(range(3),p=p_state)] # initial state
    t = 0            # initial time
    while t < tmax:
        t += dt
        update(x,s)
    return x,s

def sim_ensemble(N):
    """ N = number of molecules to simulate """
    X,S = np.zeros((1+tmax/dt,N)),np.zeros((1+tmax/dt,N))
    for i in range(N):
        x,s = markov_sim()
        X[:,i] = x
        S[:,i] = s

    t = np.linspace(0,tmax,len(x))  # time axis
    return t,X,S

In [52]:
a_levels = np.linspace(0.01,0.99,10)
b_levels = np.linspace(0.01,0.49,10)
#state_distribution = []
drift_fit,diff_fit = [],[]
for a in a_levels:
    for b in b_levels:
        Q,p_state,p_bidir = get_Q(a,b)
        t,X,S = sim_ensemble(500)

        #state_distribution.append([np.mean(S[:,i]) for i in range(S.shape[1])])
        print X.shape

        meanX = np.array([np.mean(X[i,:]) for i in range(X.shape[0])])
        varX = np.array([np.var(X[i,:]) for i in range(X.shape[0])])

        drift_fit.append(stats.linregress(t,meanX)[0])
        diff_fit.append(stats.linregress(t,varX)[0])

[[ 0.98  0.01  0.01]
 [ 0.01  0.98  0.01]
 [ 0.01  0.01  0.98]]
(121, 500)
[[ 0.87111111  0.11888889  0.01      ]
 [ 0.11888889  0.76222222  0.11888889]
 [ 0.01        0.11888889  0.87111111]]
(121, 500)
[[ 0.76222222  0.22777778  0.01      ]
 [ 0.22777778  0.54444444  0.22777778]
 [ 0.01        0.22777778  0.76222222]]
(121, 500)
[[ 0.65333333  0.33666667  0.01      ]
 [ 0.33666667  0.32666667  0.33666667]
 [ 0.01        0.33666667  0.65333333]]
(121, 500)
[[ 0.54444444  0.44555556  0.01      ]
 [ 0.44555556  0.10888889  0.44555556]
 [ 0.01        0.44555556  0.54444444]]
(121, 500)
[[ 0.43555556  0.55444444  0.01      ]
 [ 0.55444444 -0.10888889  0.55444444]
 [ 0.01        0.55444444  0.43555556]]


ValueError: probabilities are not non-negative

In [24]:
X = np.array(X)

In [ ]:
plt.figure()
plt.plot(drift_fit,'ob')
#plt.plot(a_levels,drift_fit,'ob')
#plt.plot(a_levels,drift_theory,'-r')
plt.ylim([0,1])
plt.title('drift')

plt.figure()
plt.plot(np.log(diff_fit),'ob')
#plt.plot(a_levels,np.log(diff_fit),'ob')
#plt.plot(a_levels,np.log(diff_theory),'-r')
plt.title('diffusion')

In [ ]:
plt.hist(state_distribution[-1])

In [ ]:
plt.hist([state_distribution[0]*120,state_distribution[-1]*120],20)

In [ ]:
plt.figure()
plt.plot(varX)
v_fit,D_fit = fit_drift_diffusion(p_bidir[2]-p_bidir[0],p_state[1])
plt.plot(np.arange(0,tmax,dt)*D_fit,'-r')
plt.show()

In [10]:
np.argmax([0.5,1.0,0.5])

1

In [ ]:
drift_calc = 0.5
plt.figure()
plt.plot([np.mean(X[i,:]) for i in range(X.shape[0])])
plt.plot(np.arange(0,tmax,dt)*v_fit,'-r')

In [ ]:
plt.hist(X[-1,:],30)

In [ ]:
x = np.arange(0,100,1)
y = 2*x
stats.linregress(x,y)[0]

In [ ]:
t

In [33]:
np.random.choice(range(3),p=p_bidir)

1